### PR TITLE
Fix BC for previous php versions

### PR DESCRIPTION
**Pull request by KartaviK**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
👎

**Comment by mfn** [comment]
I'm torn.

I mean the library isn't very actively developed but now suddenly carrying forward this baggage for BC reasons.. what's you justification for this?

**Comment by antonioribeiro** [comment]
Not willing to go down this road to support PHP 5.4+, and I should now probably agree with @GrahamCampbell on the current PHP version, right? :/

**Comment by antonioribeiro** [comment]
@KartaviK , I just created a new branch `7.x`. Are you able to fix these conflicts?

I think most of the changes you are doing can be possibly dropped in favor of a code that supports only PHP < 7.1, including PHPUnit version. Then we would have to keep this branch in sync with 8.x.

**Comment by GrahamCampbell** [comment]
It is still possible to run travis on those old versions btw.

**Comment by GrahamCampbell** [comment]
Example: https://github.com/schmittjoh/php-option/blob/1.5.3/.travis.yml.

**Comment by GrahamCampbell** [comment]
https://github.com/antonioribeiro/google2fa/pull/152

**Comment by antonioribeiro** [comment]
@GrahamCampbell , Yeah, I just want to free the 8.x branch to move forward, but the idea is to keep them both running on Travis. 

Thanks for all your contributions ❤️

**Comment by antonioribeiro** [comment]
Sorry, I will pass on this one.

**Comment by mfn** [comment]
Good call IMHO

**Pull request closed without merging**
