### PR TITLE
Use "hash_equals" instead of "Str::equals"

### LINKED ISSUE #26: Drop "Str" class in favor of "symfony/polyfill-php56" package
The https://packagist.org/packages/symfony/polyfill-php56 package provides `hash_equals` function (when it's missing only) and therefore:

* the `hash_equals(...)` can be used instead of `Str::equals(...)`
* the whole `Str` class can be dropped, because it's only consists of that `equals` function

### PR DESCRIPTION
**Pull request by aik099**
Closes #26

### CODE REVIEW

**Comment by barryvdh** [comment]
Or bump to 5.6 and drop the fallback (as that is the last supported version)?
(Same goes for the random_int PR)

**Comment by aik099** [comment]
Bumping PHP version just because we can bump (or PHP version no longer supported) doesn't help anybody. Unless there are specific issues, that will be solved by this bumping I'm 👎  for this.

**Comment by barryvdh** [comment]
Fair enough.
Either way, :+1: for using hash_equals and dropping the class.

**Comment by aik099** [comment]
I'm wondering if this project is dead or what. Author isn't responding to any PR/issues in months now.

**Comment by barryvdh** [comment]
Not sure, I've asked him on Twitter. Otherwise I'll create a fork sometime.

**Pull request merged**
