### PR TITLE
Delete trailing comma from parameter list to support PHP 7

### PR DESCRIPTION
**Pull request by bio**
This PR resolves an issue with a trailing comma in the setSecret parameter list to support PHP 7.

### CODE REVIEW

**Comment by Interghost** [comment]
bump, can this be merged while we are waiting for bigger PRs that include the fix?

**Comment by antonioribeiro** [comment]
Hello @bio, you need to sign your commits in order for Github to allow them to be merged. Are you able to do this?

**Comment by bio** [comment]
@antonioribeiro sure, I've signed the commit

**Comment by bio** [comment]
@antonioribeiro github is still blocking the merge because the first commit is not signed, so I created a new PR #211.

**Pull request closed without merging**
