### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by PaolaRuby**

### CODE REVIEW

**Comment by PaolaRuby** [comment]
@antonioribeiro ping :)

**Comment by PaolaRuby** [comment]
@antonioribeiro ping :)

**Comment by antonioribeiro** [comment]
Sorry for being late here, @PaolaRuby, thank you!

**Comment by williamdes** [comment]
Hi @antonioribeiro 
Could you write a GitHub release too ?
Thank you for this new version 🎉

**Pull request merged**
