### PR TITLE
Fixed dependencies

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Lock files are for apps, and will actually prevent testing on PHP 8.

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
And this lock file will actually prevent testing on PHP 8...

**Comment by GrahamCampbell** [comment]
@antonioribeiro It doesn't look like travis is actually enabled on this repo?

**Comment by antonioribeiro** [comment]
@GrahamCampbell: https://travis-ci.org/github/antonioribeiro/

**Comment by GrahamCampbell** [comment]
Does travis still have access to your account? It's status messages are not getting through. Maybe try logging in again?

**Comment by GrahamCampbell** [comment]
From what I can see, it looks like this PR does genuinely fix PHP 8.0, according to that travis build. :)

**Comment by GrahamCampbell** [comment]
NB Those removed dependencies were things needed on PHP 5.

**Comment by antonioribeiro** [comment]
image

@GrahamCampbell , Sometimes Github shows the Travis build, but others it doesn't, super odd

**Comment by mfn** [comment]
> Sometimes Github shows the Travis build, but others it doesn't, super odd

I've seen this also lately on some of my public repos 🤷‍♀️

**Pull request merged**
