### PR TITLE
Fixed broken code on PHP 5.3/5.4/5.5

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
This still isn't brilliant though. Maybe you should add a dependency on symfony's polyfil for this function?

**Comment by leandro-lugaresi** [comment]
You can use this function:
```php
/**
 * A timing safe equals comparison
 *
 * @param string $safe The internal (safe) value to be checked
 * @param string $user The user submitted (unsafe) value
 *
 * @return boolean True if the two strings are identical.
 */
function timingSafeEquals($safe, $user) {
    $safeLen = strlen($safe);
    $userLen = strlen($user);

    if ($userLen != $safeLen) {
        return false;
    }

    $result = 0;

    for ($i = 0; $i < $userLen; $i++) {
        $result |= (ord($safe[$i]) ^ ord($user[$i]));
    }

    // They are only identical strings if $result is exactly 0...
    return $result === 0;
}
```
this function is an alternative for php < 5.6

**Comment by antonioribeiro** [comment]
Symfony or Antony's Ferrara?

**Comment by antonioribeiro** [comment]
...or yours, @GrahamCampbell ?

**Comment by GrahamCampbell** [comment]
Feel free to lift the one that I added in Laravel. It's in the Str class.

**Comment by GrahamCampbell** [comment]
Make sure you attribute it to symfony in the same way I did though. :)

**Comment by antonioribeiro** [comment]
It's done

https://github.com/antonioribeiro/google2fa/commit/188ddec0752895d2869b9bd91e849647e00285f1

Tell me what you guys think about it, please.

**Comment by GrahamCampbell** [comment]
:+1:

**Pull request closed without merging**
