### PR TITLE
Fixed php version

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by KartaviK** [comment]
package can easily with php5.4+, there are some incorrect autoload instructions and test cases

**Comment by GrahamCampbell** [comment]
Nobody should be using PHP older than 7.1. There are pleanty of known security bugs.

**Comment by KartaviK** [comment]
> Nobody should be using PHP older than 7.1. There are pleanty of known security bugs.

Because of incorrect php version declaration in composer.json it will cause new BC break. For this needs next major version. You can look at packagist and see that previous versions still in use

**Comment by GrahamCampbell** [comment]
Bumping the minimum PHP version is not a BC break.

**Comment by antonioribeiro** [comment]
Having mixed feelings about this. It's not really my place to tell people what versions of software they should be using, in some cases people just can't move to a newer version and enforcing it is basically to punish them for something they can't even control, or me, right? If we needed to bump the version because there were needed PHP features, that would be a completely different scenario... Just thinking in here.

But we can probably tag a new major version (8.0) and keep 7.0 on LTS for like 2 years, right? 

But I'm also unsure why PHP 7.1, which is not even supported anymore, and not PHP 7.2 (support end on 30 Nov 2020).

About, PHP 8.0, @GrahamCampbell, did you ran the tests on it?

And what about `symfony/polyfill-php56`, we should probably remove it, right?

**Comment by antonioribeiro** [comment]
Looks like PHPUnit is not ready for 8.0 yet: https://travis-ci.org/github/antonioribeiro/google2fa/jobs/670898788

**Comment by GrahamCampbell** [comment]
@antonioribeiro PHPUnit 9 currently works without issues on PHP 8.0.

**Pull request merged**
