### PR TITLE
Code clean

### PR DESCRIPTION
**Pull request by jbrooksuk**
- Remove `.idea/` folder this should be in your global `.gitignore` file.
- Trailing lines have been striped.
- Should all be PSR-2.
- `composer.lock` should be committed for a package.
- `phpunit` is required for dev?

### CODE REVIEW

**Comment by jbrooksuk** [comment]
I can undo the alias changes if you'd rather. It's just annoying to have that facade with the same name to be aliased, but makes sense.

Good point, the backslash is not needed in this instance.

**Comment by antonioribeiro** [comment]
Please, revert those two and I'll merge them.

Thank you!

**Comment by jbrooksuk** [comment]
I've no idea how to revert just two of those commits... I can have a look.

**Comment by jbrooksuk** [comment]
I'll just recommit with those changes undone.

**Comment by jbrooksuk** [comment]
Let me squash them.

**Comment by jbrooksuk** [comment]
Ready when you are.

**Comment by antonioribeiro** [comment]
Thank you!

**Comment by jbrooksuk** [comment]
:)

**Pull request merged**
